import './sass/main.scss';
import './js/page-Home.js';
import './js/modal-film.js';
import './js/page-Library.js';
// import './js/localStorage.js';
import './js/search.js';
import './js/up-btn.js';
import './js/modalTeam.js';
import './js/spinner';
import './js/localization';
